server:
  port: ${PORT:8088}

spring:
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

security:
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://localhost:9999/users/current

---
spring:
  profiles: docker
  jpa:
    show-sql: false
  security:
    oauth2:
      resource:
        preferTokenInfo: false
        userInfoUri: http://security-server.dwfsistemas:9999/users/current
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
  instance:
    statusPageUrl: http://100.24.158.129:8088/actuator/info
    healthCheckUrl: http://100.24.158.129:8088/actuator/health
    homePageUrl: http://100.24.158.129:8088/
    hostname: 100.24.158.129
    preferIpAddress: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
